-- Statistik pembaca berita VISI Bangsa
-- Jalankan sekali di Supabase SQL Editor.

alter table public.berita
  add column if not exists views bigint not null default 0;

create or replace function public.increment_news_view(p_news_id text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_views bigint;
begin
  update public.berita
  set views = coalesce(views, 0) + 1
  where id::text = p_news_id
    and status = 'terbit'
  returning views into new_views;

  return new_views;
end;
$$;

grant execute on function public.increment_news_view(text) to anon, authenticated;


-- Statistik pengunjung website VISI Bangsa.
create table if not exists public.site_visits (
  id bigint generated by default as identity primary key,
  visitor_id text not null,
  path text not null,
  news_id text,
  created_at timestamptz not null default now()
);

create index if not exists site_visits_created_at_idx on public.site_visits (created_at desc);
create index if not exists site_visits_news_id_idx on public.site_visits (news_id);

alter table public.site_visits enable row level security;

create or replace function public.track_site_visit(
  p_path text,
  p_news_id text default null,
  p_visitor_id text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if coalesce(trim(p_visitor_id), '') = '' then return; end if;
  insert into public.site_visits(visitor_id, path, news_id)
  values (
    left(trim(p_visitor_id), 120),
    left(coalesce(trim(p_path), '/'), 500),
    nullif(left(trim(coalesce(p_news_id, '')), 120), '')
  );
end;
$$;

grant execute on function public.track_site_visit(text, text, text) to anon, authenticated;

create or replace function public.get_dashboard_stats()
returns json
language plpgsql
security definer
set search_path = ''
as $
declare
  result json;
  current_user_id uuid;
  current_email text;
begin
  current_user_id := auth.uid();

  if current_user_id is null then
    raise exception 'Unauthorized: sesi login dashboard tidak ditemukan';
  end if;

  select lower(coalesce(u.email, ''))
    into current_email
  from auth.users u
  where u.id = current_user_id;

  if current_email <> 'redaksivisbangsa@gmail.com' then
    raise exception 'Unauthorized: akun dashboard bukan akun redaksi';
  end if;

  select json_build_object(
    'today_visits',
      count(*) filter (
        where created_at >= date_trunc('day', now())
      ),
    'unique_today',
      count(distinct visitor_id) filter (
        where created_at >= date_trunc('day', now())
      ),
    'online',
      count(distinct visitor_id) filter (
        where created_at >= now() - interval '5 minutes'
      ),
    'total_visits',
      count(*),
    'top_articles',
      coalesce(
        (
          select json_agg(row_to_json(article_row))
          from (
            select
              v.news_id,
              b.judul,
              b.kategori,
              count(*) as visits
            from public.site_visits v
            join public.berita b
              on b.id::text = v.news_id
            where v.news_id is not null
              and b.status = 'terbit'
            group by v.news_id, b.judul, b.kategori
            order by count(*) desc, b.judul asc
            limit 10
          ) article_row
        ),
        '[]'::json
      )
  )
  into result
  from public.site_visits;

  return result;
end;
$$;

grant execute on function public.get_dashboard_stats()
to authenticated;


revoke execute on function public.get_dashboard_stats() from public, anon;
grant execute on function public.get_dashboard_stats() to authenticated;
