-- Statistik pembaca berita VISI Bangsa
-- Migration/source definition for visitor and article statistics.

alter table public.berita
  add column if not exists views bigint not null default 0;

create or replace function public.increment_news_view(p_news_id text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  new_views bigint;
begin
  update public.berita
  set views = coalesce(views, 0) + 1
  where id::text = p_news_id
    and status = 'terbit'
  returning views into new_views;

  return new_views;
end;
$$;

grant execute on function public.increment_news_view(text) to anon, authenticated;

create table if not exists public.site_visits (
  id bigint generated by default as identity primary key,
  visitor_id text not null,
  path text not null,
  news_id text,
  created_at timestamptz not null default now()
);

create index if not exists site_visits_created_at_idx
  on public.site_visits (created_at desc);

create index if not exists site_visits_news_id_idx
  on public.site_visits (news_id);

create index if not exists site_visits_visitor_created_at_idx
  on public.site_visits (visitor_id, created_at desc);

alter table public.site_visits enable row level security;

create or replace function public.track_site_visit(
  p_path text,
  p_news_id text default null,
  p_visitor_id text default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if coalesce(trim(p_visitor_id), '') = '' then
    return;
  end if;

  insert into public.site_visits(visitor_id, path, news_id)
  values (
    left(trim(p_visitor_id), 120),
    left(coalesce(trim(p_path), '/'), 500),
    nullif(left(trim(coalesce(p_news_id, '')), 120), '')
  );
end;
$$;

grant execute on function public.track_site_visit(text, text, text)
  to anon, authenticated;

create or replace function public.get_dashboard_stats()
returns json
language plpgsql
security definer
set search_path = ''
as $function$
declare
  result json;
  current_user_id uuid;
begin
  current_user_id := auth.uid();

  if current_user_id is null then
    raise exception 'Unauthorized: sesi login dashboard tidak ditemukan';
  end if;

  if not exists (
    select 1
    from public.admin_users au
    where au.user_id = current_user_id
  ) then
    raise exception 'Unauthorized: akun bukan akun redaksi';
  end if;

  select json_build_object(
    'today_visits',
      count(*) filter (where created_at >= date_trunc('day', now())),
    'unique_today',
      count(distinct visitor_id) filter (where created_at >= date_trunc('day', now())),
    'online',
      count(distinct visitor_id) filter (where created_at >= now() - interval '5 minutes'),
    'total_visits',
      count(*),
    'unique_total',
      count(distinct visitor_id),
    'top_articles',
      coalesce(
        (
          select json_agg(row_to_json(article_row))
          from (
            select
              b.id::text as news_id,
              b.judul,
              b.kategori,
              coalesce(b.views, 0) as visits
            from public.berita b
            where b.status = 'terbit'
              and coalesce(b.views, 0) > 0
            order by coalesce(b.views, 0) desc, b.tanggal desc, b.judul asc
            limit 10
          ) article_row
        ),
        '[]'::json
      )
  )
  into result
  from public.site_visits;

  return result;
end;
$function$;

revoke execute on function public.get_dashboard_stats() from public, anon;
grant execute on function public.get_dashboard_stats() to authenticated;
