-- Jalankan sekali di Supabase SQL Editor
create table if not exists public.kiriman (
  id bigint generated by default as identity primary key,
  jenis text not null check (jenis in ('berita','artikel')),
  nama text not null,
  email text not null,
  telepon text,
  judul text not null,
  kategori text not null,
  isi text not null,
  gambar text,
  status text not null default 'pending' check (status in ('pending','diterima','ditolak')),
  created_at timestamptz not null default now()
);

alter table public.kiriman enable row level security;

drop policy if exists "kiriman_public_insert" on public.kiriman;
create policy "kiriman_public_insert" on public.kiriman
for insert to anon, authenticated
with check (status = 'pending');

drop policy if exists "kiriman_admin_select" on public.kiriman;
create policy "kiriman_admin_select" on public.kiriman
for select to authenticated
using (true);

drop policy if exists "kiriman_admin_update" on public.kiriman;
create policy "kiriman_admin_update" on public.kiriman
for update to authenticated
using (true)
with check (true);

insert into storage.buckets (id,name,public)
values ('kiriman','kiriman',true)
on conflict (id) do update set public=true;

drop policy if exists "kiriman_storage_insert" on storage.objects;
create policy "kiriman_storage_insert" on storage.objects
for insert to anon, authenticated
with check (bucket_id='kiriman');

drop policy if exists "kiriman_storage_read" on storage.objects;
create policy "kiriman_storage_read" on storage.objects
for select to anon, authenticated
using (bucket_id='kiriman');

drop policy if exists "kiriman_storage_delete_admin" on storage.objects;
create policy "kiriman_storage_delete_admin" on storage.objects
for delete to authenticated
using (bucket_id='kiriman');